# Generated by Django 4.2.4 on 2024-05-31 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('author', models.TextField(default='COPO Project Team', max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_news_article_active', models.BooleanField(default=False)),
                ('associated_website_link', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('news_grid_colour', models.CharField(blank=True, default='#6e4e12', max_length=7, null=True)),
            ],
        ),
    ]
