# Generated by Django 4.2.4 on 2024-07-25 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.apps.copo_news.models
import src.apps.copo_news.storage
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('colour', models.CharField(default='#ffffff', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(default='COPO Project Team', max_length=200)),
                ('news_image', models.ImageField(default=src.apps.copo_news.models.default_news_image, storage=src.apps.copo_news.storage.OverwriteStorage(), upload_to=src.apps.copo_news.models.news_image_upload_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_news_article_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copo_news.newscategory')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-created_date'],
            },
        ),
    ]
