# Generated by Django 4.2.4 on 2024-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Maintenance', 'Maintenance'), ('Release', 'Release')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(blank=True, default='#690a6e', max_length=7, null=True),
        ),
    ]
