# Generated by Django 4.2.4 on 2024-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0002_alter_news_options_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(blank=True, default='#4dde8d', max_length=7, null=True),
        ),
    ]
