# Generated by Django 4.2.4 on 2024-09-10 09:06

from django.db import migrations, models
import src.apps.copo_news.models
import src.apps.copo_news.storage


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0002_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, storage=src.apps.copo_news.storage.OverwriteStorage(base_url='/media/', location='/copo/static'), upload_to=src.apps.copo_news.models.news_image_upload_path),
        ),
    ]
