# Generated by Django 4.2.4 on 2024-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0003_alter_news_news_grid_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(blank=True, default='#ffa380', max_length=7, null=True),
        ),
    ]
