# Generated by Django 4.2.4 on 2024-06-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0004_alter_news_news_grid_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(blank=True, default='#618a08', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 9, 56, 14, 114710, tzinfo=datetime.timezone.utc)),
        ),
    ]
