# Generated by Django 4.2.4 on 2024-06-03 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0005_alter_news_news_grid_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Maintenance', 'Maintenance'), ('Release', 'Release'), ('Other', 'Other')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(blank=True, default='#876ef0', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 9, 57, 27, 122326, tzinfo=datetime.timezone.utc)),
        ),
    ]
