# Generated by Django 4.2.4 on 2024-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0006_alter_news_category_alter_news_news_grid_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(blank=True, default='#b3fa8e', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
