# Generated by Django 4.2.4 on 2024-06-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0007_alter_news_news_grid_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_grid_colour',
        ),
    ]
