# Generated by Django 4.2.4 on 2024-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0008_remove_news_news_grid_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_grid_colour',
            field=models.CharField(default='#728b46', max_length=7),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
