# Generated by Django 4.2.4 on 2024-06-04 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0009_news_news_grid_colour_alter_news_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('colour', models.CharField(default='#237253', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_grid_colour',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copo_news.newscategory'),
        ),
    ]
