# Generated by Django 4.2.4 on 2024-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0010_newscategory_remove_news_news_grid_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='colour',
            field=models.CharField(default='#4a25f1', max_length=7),
        ),
    ]
