# Generated by Django 4.2.4 on 2024-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0012_alter_newscategory_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='colour',
            field=models.CharField(default='#610853', max_length=7),
        ),
    ]
