# Generated by Django 4.2.4 on 2024-06-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_news', '0014_alter_newscategory_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'News'},
        ),
    ]
