'''
Overview:
 A virtual manifest ID is a unique identifier used to link samples across different manifests and profiles.
 It is generated by concatenating the prefix 'MANIFEST-ID-VIRTUAL-' to a UUID and set to the
 'manifest_id_virtual' field in the sample records in the database.
 
 The samples can then be accessed or queried via the API: 
 https://copo-project.org/api/manifest/<virtual_manifest_id>
 where <virtual_manifest_id> is the virtual manifest ID.

Run the script: $ python shared_tools/scripts/generate_virtual_manifest_id.py

Update database records: db.SampleCollection.updateMany({"<field>":{ "$in":["<values>"]}},{"$set":{"manifest_id_virtual":"<virtual_manifest_id>"}})
'''
import uuid

prefix = 'MANIFEST-ID-VIRTUAL-'  # Length: 22 characters for virtual manifest ID
uuid_part = str(uuid.uuid4())[:36 - len(prefix)]  # Remaining length for UUID part
virtual_manifest_id = f'{prefix}{uuid_part}'
manifest_id_eg = 'f6b6fa15-9e15-446e-92ba-af9dd05725ae' # Example manifest ID

assert len(virtual_manifest_id) == 36 and len(manifest_id_eg) == 36

print('Generated virtual Manifest ID:', virtual_manifest_id)
