#it is for mac, change some of the docker images if you want to use it for linux environment
#export $(cat .env) > /dev/null 2>&1; docker compose -f local-docker-compose-mac.yaml up -d
version: "3.9"
services:
  copo_web:
    image: copo-web:3.12_24.04
    command: >
      sleep infinity
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT_TYPE=local
      - ASPERA_PLUGIN_DIRECTORY=aspera_linux_plugin
      - SECRET_KEY=${vault_copo_web_secret_key}
      - MEDIA_PATH=media/
      - DEBUG=true
      - REDIS_HOST=copo_redis
      - REDIS_PORT=6379
      - WEBIN_USER=${vault_copo_webin_user}
      - WEBIN_USER_PASSWORD=${vault_copo_webin_user_password}
      - ENA_SERVICE=https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/
      - MONGO_USER=copo_user
      - MONGO_USER_PASSWORD=password
      - MONGO_DB=copo_mongo
      - MONGO_HOST=copo_mongo
      - MONGO_PORT=27017
      - MONGO_MAX_POOL_SIZE=100
      - POSTGRES_DB=copo
      - POSTGRES_USER=copo_user
      - POSTGRES_PORT=5432
      - POSTGRES_SERVICE=copo_postgres
      - POSTGRES_PASSWORD=password
      - ORCID_SECRET=${vault_copo_orcid_secret_key}
      - ORCID_CLIENT=${vault_copo_orcid_client_id}
      - NIH_API_KEY=${vault_copo_nih_api_key}
      - PUBLIC_NAME_SERVICE_API_KEY=${vault_copo_public_name_service_api_key}
      - MAIL_PASSWORD=${vault_copo_mail_password}
      - MAIL_PORT=587
      - MAIL_ADDRESS=data@earlham.ac.uk
      - MAIL_SERVER=outlook.office365.com
      - MAIL_USERNAME=eidata@nbi.ac.uk
      - ALLOWED_HOSTS=
      - PUBLIC_NAME_SERVICE=https://id.tol.sanger.ac.uk/api/v2/
      - ENA_ENDPOINT_REPORT=https://wwwdev.ebi.ac.uk/ena/submit/report/
      - ASPERA_PATH=/root/.aspera/cli
      - BIOIMAGE_PATH=${vault_copo_bioimage_path}
      - BIOIMAGE_SERVER=bsaspera_w@hx-fasp-1.ebi.ac.uk
      - ECS_SECRET_KEY=${vault_ecs_secret_key}
      - ECS_ACCESS_KEY_ID=copo@nbi.ac.uk
      - ECS_ENDPOINT=https://ei-copo.obj-data.nbi.ac.uk
      - ENA_V2_SERVICE_SYNC=https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/submit
      - ENA_V2_SERVICE_ASYNC=https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/submit/queue
      - ENA_V1_SAMPLE_SERVICE=https://wwwdev.ebi.ac.uk/ena/submit/drop-box/samples
      - B2DROP_PERMITS=/copo/b2drop/permits
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@test.com
      - http_protocol=http
    depends_on:
      - copo_redis
      - copo_postgres
      - copo_mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - /Users/zef22hak/development/COPO_refactoring/COPO-production:/copo
  copo_redis:
    image: redis:6.2.8

  copo_postgres:
    image: postgres:15
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_DB=copo
      - POSTGRES_USER=copo_user
      - POSTGRES_PASSWORD=password

  copo_mongo:
    image: copo/copo-mongo-mac:v8.0.1
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/replica.key
    entrypoint:
       - bash
       - -c
       - |
          openssl rand -base64 756 > /data/replica.key
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@
    hostname: copo-mongo-server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=copo_admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_USER=copo_user
      - MONGO_USER_PASSWORD=password
      - MONGO_DB=copo_mongo
  #copo_browser:
  #  image: debbyku/browserless.chrome
  #  ports: 
  #    - "3000:3000"
  #  links:
  #    - copo_web:copo-new.cyverseuk.org
  #  environment:
  #    - COPO_WEB_USER=${COPO_WEB_USER}
  #    - COPO_WEB_USER_PW=${COPO_WEB_USER_PW}
  #    - COPO_WEB_URL=http://copo-new.cyverseuk.org:8000
  #    - BROWSERLESS_HTTP_URL=http://copo_browser:3000
  #    - BROWSERLESS_WS_URL=ws://copo_browser:3000
  #    - CHROME_REFRESH_TIME=1800000
  #    - CHROME_REFRESH_TIME_RANDOMNESS=10000
  #    - CHROME_ARGS=--no-sandbox,--keepalive=30000,--disable-dev-shm-usage,--disable-gpu,--disable-setuid-sandbox,--disable-software-rasterizer,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu-sandbox,--disable-infobars,--disable-notifications,--disable-extensions,--disable-web-security,--disable-features=IsolateOrigins,site-per-process,--disable-site-isolat
  #    - KEEP_ALIVE=true
  #    - PREBOOT_CHROME=true
  #    - MAX_CONCURRENT_SESSIONS=5
  #    - MAX_QUEUE_LENGTH=10
  #    - PREBOOT_QUANTITY=2
  edp:
    image: python:3.10.13-bullseye
    command: sleep infinity
    volumes:
      - /Users/zef22hak/development/EDP:/EDP
    environment:
      - SAPIOURL=${SAPIOURL}
      - SAPIOGUID=${SAPIOGUID}
      - SAPIOTOKEN=${SAPIOTOKEN}
      - ZENODOURL=https://zenodo.org/api
      - ZENODOTOKEN=${ZENODOTOKEN}
