# Generated by Django 4.2.4 on 2023-11-02 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cookie_consent_log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, null=True, size=None),
        ),
    ]
