# Generated by Django 4.2.4 on 2023-11-27 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0002_userdetails_cookie_consent_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingcentre',
            name='contact_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, null=True, size=None),
        ),
    ]
