# Generated by Django 4.2.4 on 2023-12-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0003_sequencingcentre_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingcentre',
            name='contact_details',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
