# Generated by Django 4.2.4 on 2024-05-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0004_alter_sequencingcentre_contact_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'UserDetails'},
        ),
    ]
