# Generated by Django 4.2.4 on 2024-04-25 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copo_core', '0004_alter_sequencingcentre_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingcentre',
            name='isApprovalRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssociatedProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('isApprovalRequired', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
