# Generated by Django 4.2.4 on 2024-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0004_alter_sequencingcentre_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('widget_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('widget_colour', models.CharField(blank=True, max_length=200, null=True)),
                ('widget_icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('table_id', models.CharField(max_length=100)),
                ('reverse_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RecordActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_colour', models.CharField(blank=True, help_text='Colour of the icon', max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('single', 'Single'), ('multi', 'Multiple')], default='single', max_length=100, null=True)),
                ('error_message', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100, null=True)),
                ('action', models.CharField(blank=True, help_text='Name of javascript function to be performed on click', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('template', models.CharField(max_length=500)),
                ('additional_attr', models.CharField(blank=True, help_text='Additional attributes for the button,format: key1:value1,key2:value2,key3:value3', max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('widget_colour', models.CharField(blank=True, max_length=200, null=True)),
                ('is_dtol_profile', models.BooleanField(default=False)),
                ('is_permission_required', models.BooleanField(default=True)),
                ('components', models.ManyToManyField(blank=True, to='copo_core.component')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='recordaction_buttons',
            field=models.ManyToManyField(blank=True, to='copo_core.recordactionbutton'),
        ),
        migrations.AddField(
            model_name='component',
            name='title_buttons',
            field=models.ManyToManyField(blank=True, to='copo_core.titlebutton'),
        ),
    ]
