# Generated by Django 4.2.4 on 2024-04-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0005_sequencingcentre_isapprovalrequired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associatedprofiletype',
            old_name='isApprovalRequired',
            new_name='is_approval_required',
        ),
        migrations.RenameField(
            model_name='sequencingcentre',
            old_name='isApprovalRequired',
            new_name='is_approval_required',
        ),
    ]
