# Generated by Django 4.2.4 on 2024-07-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0005_component_recordactionbutton_titlebutton_profiletype_and_more'),
        ('copo_core', '0006_rename_isapprovalrequired_associatedprofiletype_is_approval_required_and_more'),
    ]

    operations = [
    ]
