# Generated by Django 4.2.4 on 2024-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0007_merge_20240724_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewlock',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
