# Generated by Django 4.2.4 on 2024-07-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0007_merge_20240709_1609'),
        ('copo_core', '0007_merge_20240724_1558'),
    ]

    operations = [
    ]
