# Generated by Django 4.2.4 on 2024-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0008_merge_20240725_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewlock',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
