# Generated by Django 4.2.4 on 2024-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0008_alter_viewlock_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedprofiletype',
            name='acceptance_email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associatedprofiletype',
            name='is_acceptance_email_notification_required',
            field=models.BooleanField(default=False),
        ),
    ]
