# Generated by Django 4.2.4 on 2024-08-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0009_associatedprofiletype_acceptance_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='associated_profile_types',
            field=models.ManyToManyField(blank=True, to='copo_core.associatedprofiletype'),
        ),
    ]
