# Generated by Django 4.2.4 on 2024-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0009_merge_20240726_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(default='', max_length=78)),
                ('body', models.TextField(blank=True, default='', max_length=2000)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='banner_view',
        ),
    ]
