# Generated by Django 4.2.4 on 2024-08-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0010_banner_delete_banner_view'),
        ('copo_core', '0011_profiletype_post_save_action_and_more'),
    ]

    operations = [
    ]
