# Generated by Django 5.1.1 on 2025-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0012_merge_20240828_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedprofiletype',
            name='is_approval_required_for_updated_manifest',
            field=models.BooleanField(default=True),
        ),
    ]
