# Generated by Django 5.1.1 on 2025-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0013_associatedprofiletype_is_approval_required_for_updated_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='schema_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
