# Generated by Django 5.1.1 on 2025-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0014_component_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='base_component',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
