# Generated by Django 5.1.1 on 2025-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0015_component_base_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='group_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='is_assignable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='component',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
