# Generated by Django 5.1.1 on 2025-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0016_component_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='is_deprecated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
