# Generated by Django 5.1.1 on 2025-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0017_profiletype_is_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='button_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='component',
            name='order',
            field=models.PositiveIntegerField(
                default=0, editable=False,
            ),
        ),
    ]
