# Generated by Django 5.1.1 on 2025-10-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0017_profiletype_is_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='post_delete_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
