# Generated by Django 5.1.1 on 2025-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0019_tourprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='tour_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
