# Generated by Django 5.1.1 on 2025-11-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0020_component_tour_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordactionbutton',
            name='tour_id',
            field=models.CharField(blank=True, help_text='Optional tour ID for quick tours', max_length=100, null=True),
        ),
    ]
