# Generated by Django 5.1.1 on 2025-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0021_recordactionbutton_tour_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlebutton',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='titlebutton',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
